import colors from "vuetify/util/colors";
export const light = {
  dark: false,
  colors: {
    background: "#ffffff",
    "on-background": "#181826",
    "on-surface": "#181826",
    //primary: "#181826",
    primary: "#007bff", // Ahora usa el color tecnológico
    "primary-tech": "#007bff", // Azul tecnológico
    menu: "#181826",
    secondary: "#13e4e4",
    accent: "#f2c31c",
    surface: "#ffff",
    card: "#f8f8f8",
    info: "#123354",
    success: "#00BD03",
    warning: "#FFAE1F",
    error: "#FF5252",
    middle: "#ebebeb",
    buttons: "#c8c8c8",
    action: "#2563eb",
    actions: "#e87229",
    contrast: "#181826",
    teal: colors.teal.base,
  },
  variables: {
    "border-color": "#000000",
    "border-opacity": 0.12,
    "high-emphasis-opacity": 1,
    "medium-emphasis-opacity": 0.6,
    "disabled-opacity": 0.3,
    "idle-opacity": 0.04,
    "hover-opacity": 0.1,
    "focus-opacity": 0.12,
    "selected-opacity": 0.08,
    "activated-opacity": 0.12,
    "pressed-opacity": 0.12,
    "dragged-opacity": 0.08,
    "theme-kbd": "#212529",
    "theme-on-kbd": "#FFFFFF",
    "theme-code": "#F5F5F5",
    "theme-on-code": "#000000",
    "shadow-key-umbra-opacity": "rgba(0, 0, 0, 0.08)",
    "shadow-key-penumbra-opacity": "rgba(0, 0, 0, 0.06)",
    "shadow-key-ambient-opacity": "rgba(0, 0, 0, 0.04)",
  },
};

export const dark = {
  dark: true,
  colors: {
    background: "#181826",
    "on-background": "#f5f7fa",
    "on-surface": "#f5f7fa",
    primary: "#2196f3", // Ahora usa el color tecnológico para dark
    "primary-tech": "#2196f3", // Azul tecnológico para dark
    menu: "#0E0E1B",
    secondary: "#13e4e4",
    accent: "#f2c31c",
    surface: "#1e1e2e",
    card: "#252538",
    info: "#C7DEFF",
    success: "#00BD03",
    warning: "#FFAE1F",
    error: "#FF5252",
    middle: "#2a2a3e",
    buttons: "#3a3a4e",
    action: "#2563eb",
    actions: "#e87229",
    contrast: "#ffffff",
    teal: colors.teal.base,
  },
  variables: {
    "border-color": "#ffffff",
    "border-opacity": 0.12,
    "high-emphasis-opacity": 1,
    "medium-emphasis-opacity": 0.6,
    "disabled-opacity": 0.3,
    "idle-opacity": 0.04,
    "hover-opacity": 0.1,
    "focus-opacity": 0.12,
    "selected-opacity": 0.08,
    "activated-opacity": 0.12,
    "pressed-opacity": 0.12,
    "dragged-opacity": 0.08,
    "theme-kbd": "#212529",
    "theme-on-kbd": "#FFFFFF",
    "theme-code": "#2a2a3e",
    "theme-on-code": "#f5f7fa",
    "shadow-key-umbra-opacity": "rgba(0, 0, 0, 0.08)",
    "shadow-key-penumbra-opacity": "rgba(0, 0, 0, 0.06)",
    "shadow-key-ambient-opacity": "rgba(0, 0, 0, 0.04)",
  },
};
export const themes = { light, dark };
